<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome to Facebook, AndhikaUpload a pr_51e61d</name>
   <tag></tag>
   <elementGuidId>1240619c-3268-40dd-9236-d912dd4fd0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bdao358l.om3e55n1.g4tp4svg.alzwoclg.cgu29s5g.i15ihif8.aeinzg81.jcxyg2ei.o9w3sbdw.sr926ui1.jl2a5g8c.bdjfgm2q.dhod7fyx.ir39z7dx.gqe1mzv8.av1hlb45</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d104d7a3-ef43-4d12-abc0-65e433a18ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>616280c5-62a6-4ec3-8467-92fdd1aa8b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bdao358l om3e55n1 g4tp4svg alzwoclg cgu29s5g i15ihif8 aeinzg81 jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c bdjfgm2q dhod7fyx ir39z7dx gqe1mzv8 av1hlb45</value>
      <webElementGuid>2d66b8fc-a128-4ec8-ae11-dcd827e53da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to Facebook, AndhikaUpload a profile pictureAdd a photo so that friends can easily identify you.Add PictureFind people you knowSearch by name or look for schoolmates and colleagues.Get to know your privacy settingsYou control how you share your stuff with people and apps on Facebook.Take a Privacy Tour</value>
      <webElementGuid>8712b40a-0539-4416-8bba-6685c1719897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_WT&quot;)/div[1]/div[1]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg&quot;]/div[@class=&quot;g4tp4svg om3e55n1 cqf1kptm alzwoclg&quot;]/div[@class=&quot;alzwoclg cqf1kptm om3e55n1&quot;]/div[@class=&quot;alzwoclg cqf1kptm om3e55n1 kyj84mfa cofpoq2j&quot;]/div[@class=&quot;alzwoclg cqf1kptm p1t2w4gn fawcizw8 om3e55n1 g4tp4svg&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg jez8cy9q jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c fawcizw8 h93itd9g&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg jg3vgc78 cgu29s5g i15ihif8 aeinzg81 sl27f92c hael596l sr926ui1 jl2a5g8c kwmpab9d fawcizw8 red7f7t1&quot;]/div[@class=&quot;bdao358l om3e55n1 g4tp4svg alzwoclg cgu29s5g i15ihif8 aeinzg81 jcxyg2ei o9w3sbdw sr926ui1 jl2a5g8c bdjfgm2q dhod7fyx ir39z7dx gqe1mzv8 av1hlb45&quot;]</value>
      <webElementGuid>80b7ef1d-f69e-4bd5-b9a6-43ce50e6b190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_WT']/div/div/div/div[3]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>98d65817-2a03-40c5-9271-74dd0b86ab0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[1]</value>
      <webElementGuid>bc8b978b-7db9-4572-9f8b-1210301eaafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[4]</value>
      <webElementGuid>3c31f956-c2c3-41f7-a22d-5d323046fa93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>ab4fc72e-ceb6-4911-bd30-bd16f4a41910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Welcome to Facebook, AndhikaUpload a profile pictureAdd a photo so that friends can easily identify you.Add PictureFind people you knowSearch by name or look for schoolmates and colleagues.Get to know your privacy settingsYou control how you share your stuff with people and apps on Facebook.Take a Privacy Tour' or . = 'Welcome to Facebook, AndhikaUpload a profile pictureAdd a photo so that friends can easily identify you.Add PictureFind people you knowSearch by name or look for schoolmates and colleagues.Get to know your privacy settingsYou control how you share your stuff with people and apps on Facebook.Take a Privacy Tour')]</value>
      <webElementGuid>84da13fe-4176-4572-af67-3cface455bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
